name: 'Textidote Action'
description: 'Runs textidote against a latex entrypoint'
inputs:
  latex-file:
    description: 'LaTeX file to run against'
    required: true
  language:
    description: 'Language to spellcheck against'
    required: false
runs:
  using: 'docker'
  image: 'docker://ghcr.io/theconner/textidote-github-action:main'
  args:
    - --ci
    - --output
    -- workflow
    - ${{ inputs.latex-file }}